var TOPICS = {
  science: {
    'K-2': ['Animals', 'Plants', 'Weather', 'Seasons', 'Five Senses', 'Magnets', 'Water Cycle', 'Day and Night', 'Living vs Non-Living', 'Push and Pull', 'Floating and Sinking', 'Hot and Cold', 'Light and Shadows', 'Sounds Around Us', 'Rocks and Soil', 'Trees', 'My Body', 'Food Groups', 'Growing and Changing', 'Materials', 'Air and Wind', 'Rainbows', 'Seeds and Growth', 'Animal Homes', 'Animal Sounds', 'Taking Care of Pets', 'The Sun', 'Moon and Stars', 'Our Planet Earth', 'Recycling', 'Water and Ice', 'Insects', 'Birds', 'Fish', 'Baby Animals'],
    '3-5': ['Solar System', 'Ecosystems', 'Simple Machines', 'Human Body', 'Rocks & Minerals', 'Energy', 'Food Chain', 'States of Matter', 'Sound & Light', 'Weather & Climate', 'Forces', 'Electricity Basics', 'Magnetism', 'Adaptations', 'Life Cycles', 'Soil', 'Natural Resources', 'Conservation', 'Solar Energy', 'The Moon', 'Constellations', 'Volcanoes', 'Earthquakes', 'Fossils', 'Classification', 'Digestive System', 'Skeletal System', 'Muscular System', 'Respiratory System', 'Nervous System', 'Invertebrates', 'Vertebrates', 'Habitats', 'Pollution', 'Renewable Energy', 'Gravity', 'Friction'],
    '6-8': ['Photosynthesis', 'Cell Structure', 'Genetics', 'Chemistry Basics', 'Forces & Motion', 'Plate Tectonics', 'Natural Selection', 'Periodic Table', 'Electricity', 'Chemical Reactions', "Newton's Laws", 'Ecosystems & Biomes', 'Human Body Systems', 'Reproduction', 'Evolution', 'DNA', 'Atomic Structure', 'Waves', 'Light', 'Sound', 'Energy Types', 'Acids & Bases', 'Carbon Cycle', 'Climate Change', 'Rock Cycle', 'Geological Time', 'Astronomy Basics', 'Immune System', 'Circulatory System', 'Endocrine System', 'Mitosis & Meiosis', 'Diffusion & Osmosis', 'Chemical Bonding', 'Motion Graphs', 'Simple Circuits', 'Magnetic Fields', 'Weather Patterns'],
    '9-12': ['DNA & Genetics', 'Evolution', 'Chemical Reactions', "Newton's Laws", 'Thermodynamics', 'Environmental Science', 'Organic Chemistry', 'Quantum Mechanics', 'Anatomy', 'Molecular Biology', 'Biochemistry', 'Cellular Respiration', 'Protein Synthesis', 'Electrochemistry', 'Kinetics', 'Nuclear Chemistry', 'Astrophysics', 'Cosmology', 'Relativity', 'Electromagnetism', 'Fluid Dynamics', 'Ecology', 'Population Biology', 'Immunology', 'Neuroscience', 'Endocrinology', 'Botany', 'Zoology', 'Microbiology', 'Virology', 'Enzymology', 'Spectroscopy', 'Thermochemistry', 'Geophysics', 'Meteorology', 'Oceanography']
  },
  math: {
    'K-2': ['Counting', 'Addition', 'Subtraction', 'Shapes', 'Patterns', 'Measurement', 'Telling Time', 'Money', 'Number Bonds', 'Comparing Numbers', 'Place Value Basics', 'Skip Counting', 'Even and Odd', 'Ordinal Numbers', 'Graphing', 'Probability', 'Fractions Basics', 'Halves and Fourths', 'Length', 'Weight', 'Capacity', 'Temperature', 'Calendars', 'Position Words', 'Symmetry', 'Sorting', 'Tally Marks', 'Number Lines', 'Counting On', 'Making Ten', 'Doubles', 'Fact Families', 'Base Ten Blocks', 'Ten Frames'],
    '3-5': ['Multiplication', 'Division', 'Fractions', 'Decimals', 'Geometry', 'Area & Perimeter', 'Place Value', 'Rounding', 'Word Problems', 'Angles', 'Triangles', 'Quadrilaterals', 'Lines of Symmetry', 'Volume', 'Mass', 'Elapsed Time', 'Equivalent Fractions', 'Mixed Numbers', 'Comparing Fractions', 'Adding Fractions', 'Subtracting Fractions', 'Long Division', 'Multi-Digit Multiplication', 'Order of Operations', 'Prime Numbers', 'Composite Numbers', 'Factors', 'Multiples', 'Greatest Common Factor', 'Least Common Multiple', 'Coordinate Plane', 'Line Plots', 'Bar Graphs', 'Pictographs'],
    '6-8': ['Algebra Basics', 'Ratios', 'Percentages', 'Probability', 'Statistics', 'Integers', 'Equations', 'Graphing', 'Pythagorean Theorem', 'Proportions', 'Rate of Change', 'Slope', 'Linear Equations', 'Inequalities', 'Systems of Equations', 'Exponents', 'Scientific Notation', 'Square Roots', 'Rational Numbers', 'Irrational Numbers', 'Real Numbers', 'Functions', 'Domain & Range', 'Scatter Plots', 'Two-Way Tables', 'Compound Probability', 'Theoretical Probability', 'Experimental Probability', 'Volume of Solids', 'Surface Area', 'Transformations', 'Congruence', 'Similarity', 'Angle Relationships'],
    '9-12': ['Algebra I', 'Algebra II', 'Geometry', 'Trigonometry', 'Calculus', 'Statistics', 'Linear Functions', 'Quadratic Equations', 'Logarithms', 'Matrices', 'Vectors', 'Complex Numbers', 'Polynomials', 'Rational Functions', 'Exponential Functions', 'Logarithmic Functions', 'Derivatives', 'Integrals', 'Limits', 'Sequences & Series', 'Probability Distributions', 'Normal Distribution', 'Hypothesis Testing', 'Confidence Intervals', 'Correlation', 'Regression', 'Unit Circle', 'Law of Sines', 'Law of Cosines', 'Conic Sections', 'Parametric Equations', 'Polar Coordinates', 'Differential Equations', 'Linear Algebra']
  },
  history: {
    'K-2': ['Community Helpers', 'Holidays', 'Maps & Globes', 'Timelines', 'American Symbols', 'Then and Now', 'Famous Americans', 'Thanksgiving', 'Presidents Day', 'Memorial Day', 'Independence Day', 'Veterans Day', 'Martin Luther King Jr.', 'George Washington', 'Abraham Lincoln', 'The Flag', 'The Statue of Liberty', 'The White House', 'The Liberty Bell', 'Pilgrims', 'Native American Homes', 'Long Ago vs Today', 'Transportation Then and Now', 'Schools Long Ago', 'Colonial Kids', 'Pioneers', 'The First Thanksgiving', 'Patriotic Songs', 'Voting', 'Good Citizenship'],
    '3-5': ['Ancient Civilizations', 'American Revolution', 'Colonial America', 'Explorers', 'Native Americans', 'Westward Expansion', 'US Government', 'Ancient Egypt', 'Ancient Greece', 'Ancient Rome', 'Maya Civilization', 'Aztec Empire', 'Inca Empire', 'Christopher Columbus', 'Lewis and Clark', 'Pocahontas', 'The Boston Tea Party', 'The Declaration of Independence', 'The Constitution', 'The Bill of Rights', 'The Oregon Trail', 'The Gold Rush', 'The Louisiana Purchase', 'The War of 1812', 'The Underground Railroad', 'Suffrage Movement', 'The Titanic', 'The Great Wall of China', 'Medieval Knights', 'Vikings'],
    '6-8': ['World War I', 'World War II', 'Civil War', 'Constitution', 'Medieval Times', 'Ancient Rome', 'Ancient Greece', 'Industrial Revolution', 'The Renaissance', 'The Reformation', 'French Revolution', 'Napoleonic Wars', 'Colonialism', 'Imperialism', 'The Crusades', 'The Black Death', 'Magna Carta', 'The Enlightenment', 'The American Civil War', 'Reconstruction', 'The Gilded Age', 'The Progressive Era', 'Spanish-American War', 'The Roaring Twenties', 'The Great Depression', 'The New Deal', 'The Cold War', 'The Korean War', 'The Vietnam War', 'The Space Race', 'Ancient China', 'Ancient India', 'The Silk Road', 'The Mongol Empire'],
    '9-12': ['Cold War', 'Civil Rights Movement', 'US Government', 'World History', 'Economics', 'Vietnam War', 'Great Depression', 'Renaissance', 'World War I', 'World War II', 'The Holocaust', 'The Atomic Age', 'The Cuban Missile Crisis', 'The Korean War', 'The Vietnam War', 'The Civil Rights Act', 'Brown vs Board of Education', 'The Womens Suffrage Movement', 'The Progressive Movement', 'The Gilded Age', 'The Industrial Revolution', 'The French Revolution', 'The Russian Revolution', 'The Chinese Revolution', 'The Cold War Era', 'Post-War America', 'The Roaring Twenties', 'The Jazz Age', 'The New Deal', 'The Space Race', 'Globalization', 'Terrorism & Security', 'The Internet Age', 'The Information Age']
  },
  english: {
    'K-2': ['Alphabet', 'Phonics', 'Sight Words', 'Rhyming', 'Story Elements', 'Nouns & Verbs', 'Capitalization', 'Punctuation', 'Adjectives', 'Opposites', 'Word Families', 'Blends', 'Digraphs', 'Vowel Sounds', 'Consonant Sounds', 'Syllables', 'Sequencing', 'Main Idea', 'Characters', 'Setting', 'Plot', 'Beginning Middle End', 'Making Predictions', 'Comparing Stories', 'Fairy Tales', 'Fables', 'Nursery Rhymes', 'Poetry', 'Nonfiction', 'Fiction', 'Informational Text', 'Opinion Writing', 'Narrative Writing'],
    '3-5': ['Parts of Speech', 'Reading Comprehension', 'Writing Process', 'Poetry', 'Figurative Language', 'Vocabulary', 'Main Idea', 'Summarizing', 'Nouns', 'Pronouns', 'Verbs', 'Adjectives', 'Adverbs', 'Prepositions', 'Conjunctions', 'Interjections', 'Subjects and Predicates', 'Complete Sentences', 'Run-On Sentences', 'Sentence Fragments', 'Compound Sentences', 'Complex Sentences', 'Dialogue', 'Quotation Marks', 'Commas', 'Apostrophes', 'Contractions', 'Possessives', 'Synonyms', 'Antonyms', 'Homophones', 'Context Clues', 'Cause and Effect', 'Compare and Contrast'],
    '6-8': ['Grammar', 'Essay Writing', 'Literary Devices', 'Shakespeare', 'Vocabulary', 'Sentence Structure', 'Theme Analysis', 'Argument Writing', 'Figurative Language', 'Tone and Mood', 'Symbolism', 'Imagery', 'Foreshadowing', 'Flashback', 'Point of View', 'First Person', 'Third Person', 'Character Development', 'Plot Structure', 'Exposition', 'Rising Action', 'Climax', 'Falling Action', 'Resolution', 'Conflict Types', 'Man vs Self', 'Man vs Society', 'Man vs Nature', 'Thesis Statements', 'Evidence & Citations', 'Transitions', 'Counterarguments', 'Research Skills'],
    '9-12': ['Literature Analysis', 'Composition', 'Rhetoric', 'American Literature', 'British Literature', 'Research Papers', 'Critical Thinking', 'Media Literacy', 'Persuasive Writing', 'Narrative Writing', 'Expository Writing', 'Descriptive Writing', 'Literary Criticism', 'Deconstruction', 'Postmodernism', 'Modernism', 'Romanticism', 'The Gothic', 'Satire', 'Irony', 'Allegory', 'Allusion', 'Metaphor Extended', 'Diction', 'Syntax', 'Voice', 'Style Analysis', 'MLA Format', 'APA Format', 'Chicago Style', 'Annotated Bibliographies', 'Peer Review', 'Revision Strategies']
  },
  geography: {
    'K-2': ['Continents', 'Oceans', 'Maps', 'My Community', 'Landforms', 'Cardinal Directions', 'Weather & Climate', 'Globes', 'Compass Rose', 'Map Key', 'Symbols', 'Mountains', 'Rivers', 'Lakes', 'Oceans', 'Islands', 'Valleys', 'Hills', 'Plains', 'Deserts', 'Forests', 'North Pole', 'South Pole', 'Equator', 'Neighborhoods', 'Cities', 'Towns', 'Countries', 'The United States', 'Canada', 'Mexico'],
    '3-5': ['US States', 'Capitals', 'Regions', 'Climate Zones', 'Natural Resources', 'Latitude & Longitude', 'Population', 'Northeast Region', 'Southeast Region', 'Midwest Region', 'Southwest Region', 'West Region', 'Rocky Mountains', 'Appalachian Mountains', 'Mississippi River', 'Great Lakes', 'Grand Canyon', 'Death Valley', 'National Parks', 'Time Zones', 'Tropics', 'Temperate Zones', 'Polar Zones', 'Rainforests', 'Grasslands', 'Tundra', 'Taiga', 'Agriculture', 'Mining', 'Fishing'],
    '6-8': ['World Geography', 'Cultures', 'Population', 'Trade & Economy', 'Ecosystems', 'Urbanization', 'Migration', 'South America', 'Europe', 'Asia', 'Africa', 'Australia', 'Antarctica', 'The Amazon', 'The Sahara', 'The Himalayas', 'The Alps', 'The Nile River', 'Monsoons', 'Hurricanes', 'Earthquakes', 'Volcanoes', 'Tsunamis', 'Population Density', 'Megacities', 'Rural vs Urban', 'Cultural Diffusion', 'Global Trade', 'Colonialism', 'Independence Movements'],
    '9-12': ['Human Geography', 'Geopolitics', 'Urbanization', 'Climate Change', 'Cartography', 'Globalization', 'Resource Distribution', 'Political Geography', 'Population Pyramids', 'Demographic Transition', 'Migration Patterns', 'Refugee Crises', 'Economic Geography', 'Industrialization', 'Deindustrialization', 'Sustainable Development', 'Renewable Resources', 'Nonrenewable Resources', 'Food Security', 'Water Scarcity', 'Geographic Information Systems', 'Remote Sensing', 'Spatial Analysis', 'Boundary Disputes', 'Territorial Claims', 'Cultural Landscapes', 'Ethnic Enclaves', 'Gentrification', 'Carrying Capacity', 'Urban Sprawl']
  }
};

var SUBJECTS = [
  { id: 'science', label: 'Science' },
  { id: 'math', label: 'Math' },
  { id: 'history', label: 'History' },
  { id: 'english', label: 'English' },
  { id: 'geography', label: 'Geography' }
];

var GRADES = ['K-2', '3-5', '6-8', '9-12'];
